### ISSUE TITLE
I trained the model follow the tutorial, but cannot restore model parameters from logdir

### ISSUE THREAD

**Issue by fooSynaptic** [policeme/transformer-pointer-generator#26]
see my exception:
```
/transformer-pointer-generator# python pred.py 
logdir:  log/2
Traceback (most recent call last):
  File "pred.py", line 115, in <module>
    preds = Prediction(hp)
  File "pred.py", line 52, in __init__
    self._init_graph()
  File "pred.py", line 65, in _init_graph
    ckpt = self.tf.train.w(self.model_dir).all_model_checkpoint_paths[-1]
AttributeError: 'NoneType' object has no attribute 'all_model_checkpoint_paths'
```
the files located in logdir is 
```
ls log/2/ -l
总用量 187912
-rw-r--r-- 1 root root 192378898 10月 29 17:01 events.out.tfevents.1572334568.ce-ai-002
-rw-r--r-- 1 root root       449 10月 29 15:33 hparams
-rw-r--r-- 1 root root     34776 10月 29 15:35 specs
```

I donnot know why tensorflow return None while i try to `get_checkpoint_state` from log dir. Can you help me figure out this issue?

**Comment by xiongma** [comment]
you should put more trace back here
